apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
  labels:
    app.kubernetes.io/name: fastapi-traefik-datascientest-project
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: github-actions
data:
  ENVIRONMENT: "local"
  DOMAIN: "dev.fastapi.local"
  PROJECT_NAME: "FastAPI Project Dev"
  FIRST_SUPERUSER: "admin@example.com"
  BACKEND_CORS_ORIGINS: "http://localhost:8080,http://localhost:8081,https://dev.fastapi.local"
  POSTGRES_SERVER: "db-dev"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  POSTGRES_USER: "postgres"
