[fastapivm_test]
# Interne IP der Test-VM.
# Von dieser VM aus ist der Host direkt im 10.10.10.0/24-Netz erreichbar.
10.10.10.51 ansible_user=ipatsaf ansible_ssh_private_key_file=~/.ssh/id_ed25519_github_vm

[fastapivm_test:vars]
# Direkter SSH-Zugriff aus dieser VM.
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# Optionaler Fallback für Zugriffe von außerhalb dieses privaten Netzes:
# ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyJump=ipatsaf@62.210.89.4'
